"""Initial migration

Revision ID: eab89691afad
Revises: 
Create Date: 2021-09-03 22:24:00.344602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab89691afad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertising_description'), 'advertising', ['description'], unique=True)
    op.create_index(op.f('ix_advertising_title'), 'advertising', ['title'], unique=True)
    op.create_table('creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('advertising_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advertising_id'], ['advertising.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_name'), 'creator', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creator_name'), table_name='creator')
    op.drop_table('creator')
    op.drop_index(op.f('ix_advertising_title'), table_name='advertising')
    op.drop_index(op.f('ix_advertising_description'), table_name='advertising')
    op.drop_table('advertising')
    # ### end Alembic commands ###
